sudo: false
language: go
os:
- linux
- osx
go:
- 1.5
install:
- script/bootstrap
script:
- script/build
- script/test
deploy:
  provider: heroku
  buildpack: https://github.com/heroku/heroku-buildpack-go.git
  api_key:
    secure: LVlrZSSqKzdlbiv3sWoHfW1ed+rmN6Q+O1CWE6nEsxztPI9hIock0TxMWUrOWghDKgN8UKefMvHgXs8HusyX/3K4qSoeZ77CFvN0rZ/k2mZ0xWxu4xYu2/fUupwuA+N6H6DTXqV7w+4syrgrxJG8fv/17GARl2fnYL3qWljTX2E=
  app:
    master: jqplay
  skip_cleanup: true
